# coding: utf-8

"""
    Profitspi API v1

    <div><p>Welcome to the Profitspi.com API v1 Beta. Here you will find a complete description of all the current APIs. Please check back regularly as we continue to roll-out new functions.</p><p>For example, to retrieve the list of default screens use https://www.profitspi.com/api/v1/defaultscreens?api_key={api_key}&user_id={user_id}.</p> <p>Functions will return JSON or XML depending on an Accept header setting of 'application/json' or 'application/xml' respectively, with JSON being the default. The Instruments functions can also return CSV for an Accept header setting of 'text/csv'. As an alternative to an Accept header add a query parameter of 'format='JSON|XML|CSV'.</p></div>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import profitspi-sdk
from profitspi-sdk.api.user_instruments_api import UserInstrumentsApi  # noqa: E501
from profitspi-sdk.rest import ApiException


class TestUserInstrumentsApi(unittest.TestCase):
    """UserInstrumentsApi unit test stubs"""

    def setUp(self):
        self.api = profitspi-sdk.api.user_instruments_api.UserInstrumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_instruments_delete_user_calendar_holidays(self):
        """Test case for user_instruments_delete_user_calendar_holidays

        Deletes all Holidays for a User or Corporate Calendar.  # noqa: E501
        """
        pass

    def test_user_instruments_delete_user_exchange_instrument(self):
        """Test case for user_instruments_delete_user_exchange_instrument

        Deletes a specific Instrument for a User or Corporate Instrument.  # noqa: E501
        """
        pass

    def test_user_instruments_delete_user_instrument_price_history(self):
        """Test case for user_instruments_delete_user_instrument_price_history

        Deletes all price history for a User or Corporate Instrument.  # noqa: E501
        """
        pass

    def test_user_instruments_delete_user_instrument_splits(self):
        """Test case for user_instruments_delete_user_instrument_splits

        Deletes all Splits for a User or Corporate Instrument.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_calendar(self):
        """Test case for user_instruments_get_user_calendar

        Retrieves a specific User or Corporate Calendar.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_calendar_holidays(self):
        """Test case for user_instruments_get_user_calendar_holidays

        Retrieves the list of Holidays for a User or Corporate Calendar.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_calendars(self):
        """Test case for user_instruments_get_user_calendars

        Retrieves the list of User or Corporate Calendars.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_exchange(self):
        """Test case for user_instruments_get_user_exchange

        Retrieves a specific User or Corporate Exchange.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_exchange_instrument(self):
        """Test case for user_instruments_get_user_exchange_instrument

        Retrieves a specific Instrument for a User or Corporate Exchange.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_exchange_instruments(self):
        """Test case for user_instruments_get_user_exchange_instruments

        Retrieves the list of Instruments for a User or Corporate Exchange.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_exchanges(self):
        """Test case for user_instruments_get_user_exchanges

        Retrieves the list of User and Corporate Exchanges.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_instrument_price_history(self):
        """Test case for user_instruments_get_user_instrument_price_history

        Retrieves price history for a specific User or Corporate Instrument.  # noqa: E501
        """
        pass

    def test_user_instruments_get_user_instrument_splits(self):
        """Test case for user_instruments_get_user_instrument_splits

        Retrieves Splits for a specific User or Corporate Instrument.  # noqa: E501
        """
        pass

    def test_user_instruments_post_user_calendar(self):
        """Test case for user_instruments_post_user_calendar

        Adds a new User or Corporate Calendar.  # noqa: E501
        """
        pass

    def test_user_instruments_post_user_calendar_holidays(self):
        """Test case for user_instruments_post_user_calendar_holidays

        Adds one or more new Holidays to a User or Corporate Calendar.  # noqa: E501
        """
        pass

    def test_user_instruments_post_user_exchange(self):
        """Test case for user_instruments_post_user_exchange

        Adds a new User or Corporate Exchange.  # noqa: E501
        """
        pass

    def test_user_instruments_post_user_exchange_instrument(self):
        """Test case for user_instruments_post_user_exchange_instrument

        Adds a new Instrument to a User or Corporate Exchange.  # noqa: E501
        """
        pass

    def test_user_instruments_post_user_instrument_price_history(self):
        """Test case for user_instruments_post_user_instrument_price_history

        Adds / replaces price history for a User or Corporate Instrument.  # noqa: E501
        """
        pass

    def test_user_instruments_post_user_instrument_splits(self):
        """Test case for user_instruments_post_user_instrument_splits

        Adds one or more Splits to a Corporate Instrument.  # noqa: E501
        """
        pass

    def test_user_instruments_put_exchange(self):
        """Test case for user_instruments_put_exchange

        Updates a User or Corporate Exchange.  # noqa: E501
        """
        pass

    def test_user_instruments_put_user_calendar(self):
        """Test case for user_instruments_put_user_calendar

        Updates a User or Corporate Calendar.  # noqa: E501
        """
        pass

    def test_user_instruments_put_user_exchange_instrument(self):
        """Test case for user_instruments_put_user_exchange_instrument

        Updates a specific Instrument for a User or Corporate Exchange.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
