# coding: utf-8

"""
    Profitspi API v1

    <div><p>Welcome to the Profitspi.com API v1 Beta. Here you will find a complete description of all the current APIs. Please check back regularly as we continue to roll-out new functions.</p><p>For example, to retrieve the list of default screens use https://www.profitspi.com/api/v1/defaultscreens?api_key={api_key}&user_id={user_id}.</p> <p>Functions will return JSON or XML depending on an Accept header setting of 'application/json' or 'application/xml' respectively, with JSON being the default. The Instruments functions can also return CSV for an Accept header setting of 'text/csv'. As an alternative to an Accept header add a query parameter of 'format='JSON|XML|CSV'.</p></div>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import profitspi-sdk
from profitspi-sdk.api.instruments_api import InstrumentsApi  # noqa: E501
from profitspi-sdk.rest import ApiException


class TestInstrumentsApi(unittest.TestCase):
    """InstrumentsApi unit test stubs"""

    def setUp(self):
        self.api = profitspi-sdk.api.instruments_api.InstrumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_instruments_get_instrument_group_item_instruments(self):
        """Test case for instruments_get_instrument_group_item_instruments

        Retrieves the list of Instruments for a specific Instrument Group Item together with adhoc technical indicators.  # noqa: E501
        """
        pass

    def test_instruments_get_instrument_group_item_sub_types(self):
        """Test case for instruments_get_instrument_group_item_sub_types

        Retrieves the list of different subtypes for a specific Instrument Group Item.  # noqa: E501
        """
        pass

    def test_instruments_get_instrument_groups(self):
        """Test case for instruments_get_instrument_groups

        Retrieves the list of different types of Instrument Groups.  # noqa: E501
        """
        pass

    def test_instruments_get_instrument_groups_0(self):
        """Test case for instruments_get_instrument_groups_0

        Retrieves the list of different items for a specific Instrument Group.  # noqa: E501
        """
        pass

    def test_instruments_get_instrument_history(self):
        """Test case for instruments_get_instrument_history

        Retrieves historic data for a specific Instrument together with adhoc technical indicators.  # noqa: E501
        """
        pass

    def test_instruments_get_instrument_search_instruments(self):
        """Test case for instruments_get_instrument_search_instruments

        Retrieves the list of Instruments matching a search string together with adhoc technical indicators.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
