# coding: utf-8

# flake8: noqa
"""
    Profitspi API v1

    <div><p>Welcome to the Profitspi.com API v1 Beta. Here you will find a complete description of all the current APIs. Please check back regularly as we continue to roll-out new functions.</p><p>For example, to retrieve the list of default screens use https://www.profitspi.com/api/v1/defaultscreens?api_key={api_key}&user_id={user_id}.</p> <p>Functions will return JSON or XML depending on an Accept header setting of 'application/json' or 'application/xml' respectively, with JSON being the default. The Instruments functions can also return CSV for an Accept header setting of 'text/csv'. As an alternative to an Accept header add a query parameter of 'format='JSON|XML|CSV'.</p></div>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from profitspi-sdk.models.additionalresultitems import Additionalresultitems
from profitspi-sdk.models.criteriacondition import Criteriacondition
from profitspi-sdk.models.criteriaitem import Criteriaitem
from profitspi-sdk.models.criteriapair import Criteriapair
from profitspi-sdk.models.daystotest import Daystotest
from profitspi-sdk.models.defaultscreen import Defaultscreen
from profitspi-sdk.models.defaultstrategy import Defaultstrategy
from profitspi-sdk.models.indicator import Indicator
from profitspi-sdk.models.indicatoralias import Indicatoralias
from profitspi-sdk.models.indicatorinputs import Indicatorinputs
from profitspi-sdk.models.indicatorparameters import Indicatorparameters
from profitspi-sdk.models.indicatortype import Indicatortype
from profitspi-sdk.models.instrumentgroup import Instrumentgroup
from profitspi-sdk.models.instrumentgroupitem import Instrumentgroupitem
from profitspi-sdk.models.instrumentgroupiteminstruments import Instrumentgroupiteminstruments
from profitspi-sdk.models.instrumentgroupitemsubtype import Instrumentgroupitemsubtype
from profitspi-sdk.models.instrumenthistory import Instrumenthistory
from profitspi-sdk.models.instrumentresult import Instrumentresult
from profitspi-sdk.models.instrumentsearchinstruments import Instrumentsearchinstruments
from profitspi-sdk.models.itemcalculation import Itemcalculation
from profitspi-sdk.models.itemcalculationparameter import Itemcalculationparameter
from profitspi-sdk.models.itemcustominput import Itemcustominput
from profitspi-sdk.models.itemcustominputparameter import Itemcustominputparameter
from profitspi-sdk.models.itemdefinition import Itemdefinition
from profitspi-sdk.models.object import Object
from profitspi-sdk.models.paging import Paging
from profitspi-sdk.models.period import Period
from profitspi-sdk.models.positionentrypricetype import Positionentrypricetype
from profitspi-sdk.models.positionexitpricetype import Positionexitpricetype
from profitspi-sdk.models.positionroundingamount import Positionroundingamount
from profitspi-sdk.models.positionsizingtype import Positionsizingtype
from profitspi-sdk.models.screen import Screen
from profitspi-sdk.models.screencriteria import Screencriteria
from profitspi-sdk.models.screenresult import Screenresult
from profitspi-sdk.models.screenresults import Screenresults
from profitspi-sdk.models.stoplossexitpricetype import Stoplossexitpricetype
from profitspi-sdk.models.strategy import Strategy
from profitspi-sdk.models.strategytest import Strategytest
from profitspi-sdk.models.strategytestcosts import Strategytestcosts
from profitspi-sdk.models.strategytestcriteria import Strategytestcriteria
from profitspi-sdk.models.strategytestdate import Strategytestdate
from profitspi-sdk.models.strategytesthistory import Strategytesthistory
from profitspi-sdk.models.strategytestperiod import Strategytestperiod
from profitspi-sdk.models.strategytestpositionsizing import Strategytestpositionsizing
from profitspi-sdk.models.strategytestresults import Strategytestresults
from profitspi-sdk.models.strategytestsettings import Strategytestsettings
from profitspi-sdk.models.strategyteststopsandtargets import Strategyteststopsandtargets
from profitspi-sdk.models.strategytestsummary import Strategytestsummary
from profitspi-sdk.models.strategytesttrade import Strategytesttrade
from profitspi-sdk.models.strategytesttrades import Strategytesttrades
from profitspi-sdk.models.targetexitpricetype import Targetexitpricetype
from profitspi-sdk.models.timestopexitpricetype import Timestopexitpricetype
from profitspi-sdk.models.trailingstoplossexitpricetype import Trailingstoplossexitpricetype
from profitspi-sdk.models.trailingstoplosspricetouse import Trailingstoplosspricetouse
from profitspi-sdk.models.usercalendar import Usercalendar
from profitspi-sdk.models.usercalendarholiday import Usercalendarholiday
from profitspi-sdk.models.userexchange import Userexchange
from profitspi-sdk.models.userexchangeinstrument import Userexchangeinstrument
from profitspi-sdk.models.userinstrumentpricehistory import Userinstrumentpricehistory
from profitspi-sdk.models.userinstrumentsplit import Userinstrumentsplit
from profitspi-sdk.models.userscreen import Userscreen
