# coding: utf-8

"""
    Profitspi API v1

    <div><p>Welcome to the Profitspi.com API v1 Beta. Here you will find a complete description of all the current APIs. Please check back regularly as we continue to roll-out new functions.</p><p>For example, to retrieve the list of default screens use https://www.profitspi.com/api/v1/defaultscreens?api_key={api_key}&user_id={user_id}.</p> <p>Functions will return JSON or XML depending on an Accept header setting of 'application/json' or 'application/xml' respectively, with JSON being the default. The Instruments functions can also return CSV for an Accept header setting of 'text/csv'. As an alternative to an Accept header add a query parameter of 'format='JSON|XML|CSV'.</p></div>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from profitspi-sdk.configuration import Configuration


class Indicatorparameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parameter_name': 'str',
        'parameter_dotnettype': 'str',
        'parameter_default': 'float',
        'parameter_min_value': 'float',
        'parameter_max_value': 'float'
    }

    attribute_map = {
        'parameter_name': 'parameter_name',
        'parameter_dotnettype': 'parameter_dotnettype',
        'parameter_default': 'parameter_default',
        'parameter_min_value': 'parameter_min_value',
        'parameter_max_value': 'parameter_max_value'
    }

    def __init__(self, parameter_name=None, parameter_dotnettype=None, parameter_default=None, parameter_min_value=None, parameter_max_value=None, _configuration=None):  # noqa: E501
        """Indicatorparameters - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._parameter_name = None
        self._parameter_dotnettype = None
        self._parameter_default = None
        self._parameter_min_value = None
        self._parameter_max_value = None
        self.discriminator = None

        if parameter_name is not None:
            self.parameter_name = parameter_name
        if parameter_dotnettype is not None:
            self.parameter_dotnettype = parameter_dotnettype
        if parameter_default is not None:
            self.parameter_default = parameter_default
        if parameter_min_value is not None:
            self.parameter_min_value = parameter_min_value
        if parameter_max_value is not None:
            self.parameter_max_value = parameter_max_value

    @property
    def parameter_name(self):
        """Gets the parameter_name of this Indicatorparameters.  # noqa: E501


        :return: The parameter_name of this Indicatorparameters.  # noqa: E501
        :rtype: str
        """
        return self._parameter_name

    @parameter_name.setter
    def parameter_name(self, parameter_name):
        """Sets the parameter_name of this Indicatorparameters.


        :param parameter_name: The parameter_name of this Indicatorparameters.  # noqa: E501
        :type: str
        """

        self._parameter_name = parameter_name

    @property
    def parameter_dotnettype(self):
        """Gets the parameter_dotnettype of this Indicatorparameters.  # noqa: E501


        :return: The parameter_dotnettype of this Indicatorparameters.  # noqa: E501
        :rtype: str
        """
        return self._parameter_dotnettype

    @parameter_dotnettype.setter
    def parameter_dotnettype(self, parameter_dotnettype):
        """Sets the parameter_dotnettype of this Indicatorparameters.


        :param parameter_dotnettype: The parameter_dotnettype of this Indicatorparameters.  # noqa: E501
        :type: str
        """

        self._parameter_dotnettype = parameter_dotnettype

    @property
    def parameter_default(self):
        """Gets the parameter_default of this Indicatorparameters.  # noqa: E501


        :return: The parameter_default of this Indicatorparameters.  # noqa: E501
        :rtype: float
        """
        return self._parameter_default

    @parameter_default.setter
    def parameter_default(self, parameter_default):
        """Sets the parameter_default of this Indicatorparameters.


        :param parameter_default: The parameter_default of this Indicatorparameters.  # noqa: E501
        :type: float
        """

        self._parameter_default = parameter_default

    @property
    def parameter_min_value(self):
        """Gets the parameter_min_value of this Indicatorparameters.  # noqa: E501


        :return: The parameter_min_value of this Indicatorparameters.  # noqa: E501
        :rtype: float
        """
        return self._parameter_min_value

    @parameter_min_value.setter
    def parameter_min_value(self, parameter_min_value):
        """Sets the parameter_min_value of this Indicatorparameters.


        :param parameter_min_value: The parameter_min_value of this Indicatorparameters.  # noqa: E501
        :type: float
        """

        self._parameter_min_value = parameter_min_value

    @property
    def parameter_max_value(self):
        """Gets the parameter_max_value of this Indicatorparameters.  # noqa: E501


        :return: The parameter_max_value of this Indicatorparameters.  # noqa: E501
        :rtype: float
        """
        return self._parameter_max_value

    @parameter_max_value.setter
    def parameter_max_value(self, parameter_max_value):
        """Sets the parameter_max_value of this Indicatorparameters.


        :param parameter_max_value: The parameter_max_value of this Indicatorparameters.  # noqa: E501
        :type: float
        """

        self._parameter_max_value = parameter_max_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Indicatorparameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Indicatorparameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Indicatorparameters):
            return True

        return self.to_dict() != other.to_dict()
