# coding: utf-8

"""
    Profitspi API v1

    <div><p>Welcome to the Profitspi.com API v1 Beta. Here you will find a complete description of all the current APIs. Please check back regularly as we continue to roll-out new functions.</p><p>For example, to retrieve the list of default screens use https://www.profitspi.com/api/v1/defaultscreens?api_key={api_key}&user_id={user_id}.</p> <p>Functions will return JSON or XML depending on an Accept header setting of 'application/json' or 'application/xml' respectively, with JSON being the default. The Instruments functions can also return CSV for an Accept header setting of 'text/csv'. As an alternative to an Accept header add a query parameter of 'format='JSON|XML|CSV'.</p></div>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from profitspi-sdk.configuration import Configuration


class Screenresults(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'screen_date': 'datetime',
        'sort_column_index': 'int',
        'sort_is_descending': 'bool',
        'results': 'list[Screenresult]',
        'paging': 'Paging'
    }

    attribute_map = {
        'screen_date': 'screen_date',
        'sort_column_index': 'sort_column_index',
        'sort_is_descending': 'sort_is_descending',
        'results': 'results',
        'paging': 'paging'
    }

    def __init__(self, screen_date=None, sort_column_index=None, sort_is_descending=None, results=None, paging=None, _configuration=None):  # noqa: E501
        """Screenresults - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._screen_date = None
        self._sort_column_index = None
        self._sort_is_descending = None
        self._results = None
        self._paging = None
        self.discriminator = None

        if screen_date is not None:
            self.screen_date = screen_date
        if sort_column_index is not None:
            self.sort_column_index = sort_column_index
        if sort_is_descending is not None:
            self.sort_is_descending = sort_is_descending
        if results is not None:
            self.results = results
        if paging is not None:
            self.paging = paging

    @property
    def screen_date(self):
        """Gets the screen_date of this Screenresults.  # noqa: E501


        :return: The screen_date of this Screenresults.  # noqa: E501
        :rtype: datetime
        """
        return self._screen_date

    @screen_date.setter
    def screen_date(self, screen_date):
        """Sets the screen_date of this Screenresults.


        :param screen_date: The screen_date of this Screenresults.  # noqa: E501
        :type: datetime
        """

        self._screen_date = screen_date

    @property
    def sort_column_index(self):
        """Gets the sort_column_index of this Screenresults.  # noqa: E501


        :return: The sort_column_index of this Screenresults.  # noqa: E501
        :rtype: int
        """
        return self._sort_column_index

    @sort_column_index.setter
    def sort_column_index(self, sort_column_index):
        """Sets the sort_column_index of this Screenresults.


        :param sort_column_index: The sort_column_index of this Screenresults.  # noqa: E501
        :type: int
        """

        self._sort_column_index = sort_column_index

    @property
    def sort_is_descending(self):
        """Gets the sort_is_descending of this Screenresults.  # noqa: E501


        :return: The sort_is_descending of this Screenresults.  # noqa: E501
        :rtype: bool
        """
        return self._sort_is_descending

    @sort_is_descending.setter
    def sort_is_descending(self, sort_is_descending):
        """Sets the sort_is_descending of this Screenresults.


        :param sort_is_descending: The sort_is_descending of this Screenresults.  # noqa: E501
        :type: bool
        """

        self._sort_is_descending = sort_is_descending

    @property
    def results(self):
        """Gets the results of this Screenresults.  # noqa: E501


        :return: The results of this Screenresults.  # noqa: E501
        :rtype: list[Screenresult]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this Screenresults.


        :param results: The results of this Screenresults.  # noqa: E501
        :type: list[Screenresult]
        """

        self._results = results

    @property
    def paging(self):
        """Gets the paging of this Screenresults.  # noqa: E501


        :return: The paging of this Screenresults.  # noqa: E501
        :rtype: Paging
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """Sets the paging of this Screenresults.


        :param paging: The paging of this Screenresults.  # noqa: E501
        :type: Paging
        """

        self._paging = paging

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Screenresults, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Screenresults):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Screenresults):
            return True

        return self.to_dict() != other.to_dict()
