# coding: utf-8

"""
    Profitspi API v1

    <div><p>Welcome to the Profitspi.com API v1 Beta. Here you will find a complete description of all the current APIs. Please check back regularly as we continue to roll-out new functions.</p><p>For example, to retrieve the list of default screens use https://www.profitspi.com/api/v1/defaultscreens?api_key={api_key}&user_id={user_id}.</p> <p>Functions will return JSON or XML depending on an Accept header setting of 'application/json' or 'application/xml' respectively, with JSON being the default. The Instruments functions can also return CSV for an Accept header setting of 'text/csv'. As an alternative to an Accept header add a query parameter of 'format='JSON|XML|CSV'.</p></div>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from profitspi-sdk.configuration import Configuration


class Strategytestsettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'test_period': 'Strategytestperiod',
        'equity_and_position_sizing': 'Strategytestpositionsizing',
        'stops_and_targets': 'Strategyteststopsandtargets',
        'costs': 'Strategytestcosts'
    }

    attribute_map = {
        'test_period': 'test_period',
        'equity_and_position_sizing': 'equity_and_position_sizing',
        'stops_and_targets': 'stops_and_targets',
        'costs': 'costs'
    }

    def __init__(self, test_period=None, equity_and_position_sizing=None, stops_and_targets=None, costs=None, _configuration=None):  # noqa: E501
        """Strategytestsettings - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._test_period = None
        self._equity_and_position_sizing = None
        self._stops_and_targets = None
        self._costs = None
        self.discriminator = None

        if test_period is not None:
            self.test_period = test_period
        if equity_and_position_sizing is not None:
            self.equity_and_position_sizing = equity_and_position_sizing
        if stops_and_targets is not None:
            self.stops_and_targets = stops_and_targets
        if costs is not None:
            self.costs = costs

    @property
    def test_period(self):
        """Gets the test_period of this Strategytestsettings.  # noqa: E501


        :return: The test_period of this Strategytestsettings.  # noqa: E501
        :rtype: Strategytestperiod
        """
        return self._test_period

    @test_period.setter
    def test_period(self, test_period):
        """Sets the test_period of this Strategytestsettings.


        :param test_period: The test_period of this Strategytestsettings.  # noqa: E501
        :type: Strategytestperiod
        """

        self._test_period = test_period

    @property
    def equity_and_position_sizing(self):
        """Gets the equity_and_position_sizing of this Strategytestsettings.  # noqa: E501


        :return: The equity_and_position_sizing of this Strategytestsettings.  # noqa: E501
        :rtype: Strategytestpositionsizing
        """
        return self._equity_and_position_sizing

    @equity_and_position_sizing.setter
    def equity_and_position_sizing(self, equity_and_position_sizing):
        """Sets the equity_and_position_sizing of this Strategytestsettings.


        :param equity_and_position_sizing: The equity_and_position_sizing of this Strategytestsettings.  # noqa: E501
        :type: Strategytestpositionsizing
        """

        self._equity_and_position_sizing = equity_and_position_sizing

    @property
    def stops_and_targets(self):
        """Gets the stops_and_targets of this Strategytestsettings.  # noqa: E501


        :return: The stops_and_targets of this Strategytestsettings.  # noqa: E501
        :rtype: Strategyteststopsandtargets
        """
        return self._stops_and_targets

    @stops_and_targets.setter
    def stops_and_targets(self, stops_and_targets):
        """Sets the stops_and_targets of this Strategytestsettings.


        :param stops_and_targets: The stops_and_targets of this Strategytestsettings.  # noqa: E501
        :type: Strategyteststopsandtargets
        """

        self._stops_and_targets = stops_and_targets

    @property
    def costs(self):
        """Gets the costs of this Strategytestsettings.  # noqa: E501


        :return: The costs of this Strategytestsettings.  # noqa: E501
        :rtype: Strategytestcosts
        """
        return self._costs

    @costs.setter
    def costs(self, costs):
        """Sets the costs of this Strategytestsettings.


        :param costs: The costs of this Strategytestsettings.  # noqa: E501
        :type: Strategytestcosts
        """

        self._costs = costs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Strategytestsettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Strategytestsettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Strategytestsettings):
            return True

        return self.to_dict() != other.to_dict()
