# coding: utf-8

"""
    Profitspi API v1

    <div><p>Welcome to the Profitspi.com API v1 Beta. Here you will find a complete description of all the current APIs. Please check back regularly as we continue to roll-out new functions.</p><p>For example, to retrieve the list of default screens use https://www.profitspi.com/api/v1/defaultscreens?api_key={api_key}&user_id={user_id}.</p> <p>Functions will return JSON or XML depending on an Accept header setting of 'application/json' or 'application/xml' respectively, with JSON being the default. The Instruments functions can also return CSV for an Accept header setting of 'text/csv'. As an alternative to an Accept header add a query parameter of 'format='JSON|XML|CSV'.</p></div>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from profitspi-sdk.configuration import Configuration


class Userscreen(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'screen_id': 'int',
        'name': 'str',
        'instrument_group_text': 'str',
        'criteria_text': 'str',
        'last_accessed': 'datetime',
        'is_public': 'bool'
    }

    attribute_map = {
        'screen_id': 'screen_id',
        'name': 'name',
        'instrument_group_text': 'instrument_group_text',
        'criteria_text': 'criteria_text',
        'last_accessed': 'last_accessed',
        'is_public': 'is_public'
    }

    def __init__(self, screen_id=None, name=None, instrument_group_text=None, criteria_text=None, last_accessed=None, is_public=None, _configuration=None):  # noqa: E501
        """Userscreen - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._screen_id = None
        self._name = None
        self._instrument_group_text = None
        self._criteria_text = None
        self._last_accessed = None
        self._is_public = None
        self.discriminator = None

        if screen_id is not None:
            self.screen_id = screen_id
        if name is not None:
            self.name = name
        if instrument_group_text is not None:
            self.instrument_group_text = instrument_group_text
        if criteria_text is not None:
            self.criteria_text = criteria_text
        if last_accessed is not None:
            self.last_accessed = last_accessed
        if is_public is not None:
            self.is_public = is_public

    @property
    def screen_id(self):
        """Gets the screen_id of this Userscreen.  # noqa: E501


        :return: The screen_id of this Userscreen.  # noqa: E501
        :rtype: int
        """
        return self._screen_id

    @screen_id.setter
    def screen_id(self, screen_id):
        """Sets the screen_id of this Userscreen.


        :param screen_id: The screen_id of this Userscreen.  # noqa: E501
        :type: int
        """

        self._screen_id = screen_id

    @property
    def name(self):
        """Gets the name of this Userscreen.  # noqa: E501


        :return: The name of this Userscreen.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Userscreen.


        :param name: The name of this Userscreen.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def instrument_group_text(self):
        """Gets the instrument_group_text of this Userscreen.  # noqa: E501


        :return: The instrument_group_text of this Userscreen.  # noqa: E501
        :rtype: str
        """
        return self._instrument_group_text

    @instrument_group_text.setter
    def instrument_group_text(self, instrument_group_text):
        """Sets the instrument_group_text of this Userscreen.


        :param instrument_group_text: The instrument_group_text of this Userscreen.  # noqa: E501
        :type: str
        """

        self._instrument_group_text = instrument_group_text

    @property
    def criteria_text(self):
        """Gets the criteria_text of this Userscreen.  # noqa: E501


        :return: The criteria_text of this Userscreen.  # noqa: E501
        :rtype: str
        """
        return self._criteria_text

    @criteria_text.setter
    def criteria_text(self, criteria_text):
        """Sets the criteria_text of this Userscreen.


        :param criteria_text: The criteria_text of this Userscreen.  # noqa: E501
        :type: str
        """

        self._criteria_text = criteria_text

    @property
    def last_accessed(self):
        """Gets the last_accessed of this Userscreen.  # noqa: E501


        :return: The last_accessed of this Userscreen.  # noqa: E501
        :rtype: datetime
        """
        return self._last_accessed

    @last_accessed.setter
    def last_accessed(self, last_accessed):
        """Sets the last_accessed of this Userscreen.


        :param last_accessed: The last_accessed of this Userscreen.  # noqa: E501
        :type: datetime
        """

        self._last_accessed = last_accessed

    @property
    def is_public(self):
        """Gets the is_public of this Userscreen.  # noqa: E501


        :return: The is_public of this Userscreen.  # noqa: E501
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this Userscreen.


        :param is_public: The is_public of this Userscreen.  # noqa: E501
        :type: bool
        """

        self._is_public = is_public

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Userscreen, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Userscreen):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Userscreen):
            return True

        return self.to_dict() != other.to_dict()
